# Netlify deployment settings
[build]
  base = "frontend/"
  publish = "dist/"
  command = "bun install && bun run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
